= Migration guide

== Context
Starting with Rancher v2.13, {product_name} gets installed as part of Rancher, eliminating the need for a separate deployment. Prior to upgrading to Rancher v2.13, users are required to follow this guide to ensure a smooth upgrade process.

== Migration

Follow the steps below in order, _before_ upgrading to Rancher v2.13:

. Ensure that you upgrade {product_name} to v0.24.3. This step is important because all patch releases for v0.24 prepare the cluster for the upgrade to Rancher v2.13.
. Uninstall {product_name}. This is necessary because from Rancher v2.13 onwards, {product_name} is no longer an opt-in addon but a Rancher system component. As such, Rancher installs it in a different namespace than before and therefore the previously installed version needs to be manually uninstalled. Uninstalling v0.24.3 of {product_name} removes the core CAPI provider itself but keeps the core CAPI CRDs. At this point, the core CAPI controller should not be running on the cluster but any downstream CAPI clusters should continue to run as usual.
. Run the following kubectl commands:
+
[source,bash]
----
kubectl patch crd capiproviders.turtles-capi.cattle.io --type=json -p='[{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "cattle-turtles-system"}]'
kubectl patch crd clusterctlconfigs.turtles-capi.cattle.io --type=json -p='[{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "cattle-turtles-system"}]'
----
These commands will patch the `capiprovider` and `clusterctlconfig` CRDs so that they become adopted by {product_name} when installed as part of Rancher v2.13. 

Note, that the migration described above is necessary for users running {product_name} versions &le; v0.24.3. New users that are installing Rancher v2.13 do not need to perform any migration.